version: 2.1


# Define a job to be invoked later in a workflow.

# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs

jobs:

  default-job:
    docker:
      - image: cimg/php:7.4


    # Add steps to the job

    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps

    steps:

      # Checkout the code as the first step.

      - checkout

      - run:
          name: "install dependencies"

          command: "composer install --no-interaction --prefer-dist"
      - run:

          name: "show php version"

          command: "php -v && composer --version && php artisan -V"


# Orchestrate jobs using workflows

# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows

workflows:

  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.

    # Inside the workflow, you define the jobs you want to run.

    jobs:

      - say-hello